'use client';

import jsPDF from 'jspdf';
import { Language } from '@/i18n';

// Define types for technical specifications
export type SpecificationItem = {
  name: string;
  value: string;
};

export type ProductSpecifications = {
  technicalSpecs: SpecificationItem[];
  integrationCapabilities: SpecificationItem[];
  certifications: SpecificationItem[];
};

// Translations for PDF content
const pdfTranslations = {
  en: {
    title: 'Technical Specifications',
    physicalSpecs: 'Physical & Performance Specifications',
    integrationCapabilities: 'Integration Capabilities',
    certifications: 'Certifications & Compliance',
    generatedBy: 'Generated by TP@CK',
    page: 'Page',
    of: 'of',
  },
  fr: {
    title: 'Spécifications Techniques',
    physicalSpecs: 'Spécifications Physiques et de Performance',
    integrationCapabilities: 'Capacités d\'Intégration',
    certifications: 'Certifications et Conformité',
    generatedBy: 'Généré par TP@CK',
    page: 'Page',
    of: 'sur',
  },
  de: {
    title: 'Technische Spezifikationen',
    physicalSpecs: 'Physische & Leistungsspezifikationen',
    integrationCapabilities: 'Integrationsfähigkeiten',
    certifications: 'Zertifizierungen & Konformität',
    generatedBy: 'Erstellt von TP@CK',
    page: 'Seite',
    of: 'von',
  },
};

/**
 * Generates a PDF with technical specifications for a product
 * @param productName Name of the product (T20, T30, T50)
 * @param specs Product specifications object
 * @param language Language code (en, fr, de)
 * @returns Blob of the generated PDF
 */
export const generateProductSpecsPDF = (
  productName: string,
  specs: ProductSpecifications,
  language: Language = 'en'
): Blob => {
  // Create a new PDF document
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Get translations for the selected language
  const translations = pdfTranslations[language] || pdfTranslations.en;

  // Set font
  pdf.setFont('helvetica', 'normal');

  // Add header
  pdf.setFillColor(0, 128, 0); // Green color for header
  pdf.rect(0, 0, 210, 30, 'F');
  pdf.setTextColor(255, 255, 255); // White text
  pdf.setFontSize(24);
  pdf.text(`${translations.title} - ${productName}`, 105, 20, { align: 'center' });

  // Reset text color for body
  pdf.setTextColor(0, 0, 0);

  // Current Y position for content
  let yPos = 40;

  // Add Physical & Performance Specifications
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(translations.physicalSpecs, 20, yPos);
  yPos += 10;

  // Add specs
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  specs.technicalSpecs.forEach((spec) => {
    pdf.text(`${spec.name}: ${spec.value}`, 25, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }
  });

  yPos += 5;

  // Add Integration Capabilities
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(translations.integrationCapabilities, 20, yPos);
  yPos += 10;

  // Add integration capabilities
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  specs.integrationCapabilities.forEach((spec) => {
    pdf.text(`${spec.name}: ${spec.value}`, 25, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }
  });

  yPos += 5;

  // Add Certifications
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(translations.certifications, 20, yPos);
  yPos += 10;

  // Add certifications
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  specs.certifications.forEach((spec) => {
    pdf.text(`${spec.name}: ${spec.value}`, 25, yPos);
    yPos += 8;

    // Check if we need a new page
    if (yPos > 270) {
      pdf.addPage();
      yPos = 20;
    }
  });

  // Add footer with page numbers
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(
      `${translations.page} ${i} ${translations.of} ${pageCount}`,
      105,
      285,
      { align: 'center' }
    );
    pdf.text(
      `${translations.generatedBy} | www.tpack.fr`,
      105,
      292,
      { align: 'center' }
    );
  }

  // Return the PDF as a blob
  return pdf.output('blob');
};

/**
 * Generates and triggers download of a PDF with product specifications
 * @param productName Name of the product (T20, T30, T50)
 * @param specs Product specifications object
 * @param language Language code (en, fr, de)
 */
export const downloadProductSpecsPDF = (
  productName: string,
  specs: ProductSpecifications,
  language: Language = 'en'
): void => {
  const blob = generateProductSpecsPDF(productName, specs, language);
  const url = URL.createObjectURL(blob);

  // Create a temporary link element
  const link = document.createElement('a');
  link.href = url;
  link.download = `${productName}_${translations[language]?.title || 'Technical_Specifications'}.pdf`;

  // Append to the document, click it, and remove it
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up the URL object
  URL.revokeObjectURL(url);
};

// Translations for file names
const translations = {
  en: {
    title: 'Technical_Specifications',
  },
  fr: {
    title: 'Specifications_Techniques',
  },
  de: {
    title: 'Technische_Spezifikationen',
  },
};
